include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.config.dart"
linter:
  rules:
    file_names: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
