class Strings {
  Strings._();

  static const String appName = 'GPT Detector';
  static const String privacyPolicyUrl = 'https://cem256.github.io/GPT-Detector/privacy-policy.html';
  static const String privacyPolicy = 'Privacy Policy';
  static const String version = 'Version 1.0.0';
  static const String drawerInfo = 'Info';
  static const String drawerInfoText =
      'GPT Detector uses GPT-2 Output Detector model to identify if text is written by a human or generated by Chat GPT';
  static const String infoText1 =
      'Welcome to GPT Detector! Our app uses GPT-2 Output Detector model to identify if text is written by a human or generated by Chat GPT';
  static const String infoText2 = 'For the best results, please use English text';
  static const String infoText3 = 'The results start to get reliable after around 100 tokens.';
  static const String getStarted = 'Get Started';
  static const String networkFailure = 'Oops, it looks like we are having trouble connecting to the server';
  static const String noInternetFailure =
      "Looks like you're disconnected. Check your internet connection and give it another try";
  static const String percentOriginal = '% Original';
  static const String percentAI = '% AI';
  static const String textFieldHint = 'Paste text or write here';
  static const String textFieldError = 'Input cannot be empty';
  static const String textFieldHelper = 'For best results, use at least 100 tokens';
  static const String textFieldCounter = 'Tokens:';
  static const String analyzeButton = 'Analyze Text';
}
