class Strings {
  Strings._();

  static const String appName = 'GPT Detector';
  static const String privacyPolicyUrl = 'https://cem256.github.io/GPT-Detector/privacy-policy.html';
  static const String privacyPolicy = 'Privacy Policy';
  static const String version = 'Version 1.0.0';
  static const String drawerInfo = 'Info';
  static const String infoText1 =
      'GPT Detector uses the GPT-2 Output Detector model to identify if a text is written by a human or generated by Chat GPT.';
  static const String infoText2 =
      'The GPT-2 Text Detector may give incorrect results for text not written in English. For optimal results, use with English text only.';
  static const String infoText3 = 'Please note that results become more reliable after 100 tokens.';
  static const String getStarted = 'Get Started';
  static const String networkFailure = 'Oops, it looks like we are having trouble connecting to the server.';
  static const String noInternetFailure =
      'Looks like you\'re disconnected. Check your internet connection and give it another try.';
  static const String percentOriginal = '% Original';
  static const String percentAI = '% AI';
  static const String textFieldHint = 'Paste text or write here';
  static const String textFieldError = 'Input cannot be empty';
  static const String textFieldHelper = 'Results become more reliable after 100 tokens.';
  static const String textFieldCounter = 'Tokens:';
  static const String analyzeButton = 'Analyze Text';
}
